# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np
print(np.__version__)

1.26.4


2) Создать нулевой вектор размера 10

In [2]:
zero_vector = np.zeros(10)
print(zero_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [3]:
seven_vector = np.full(7, 7)
print(seven_vector)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
even_vector = np.arange(10, 101, 2)
print(even_vector)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
random_array = np.random.rand(10)
print(random_array)
print(random_array[::-1])

[0.10505338 0.7006509  0.06168462 0.391427   0.82726315 0.3781904
 0.23468773 0.82624198 0.89591445 0.94819234]
[0.94819234 0.89591445 0.82624198 0.23468773 0.3781904  0.82726315
 0.391427   0.06168462 0.7006509  0.10505338]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [6]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [8]:
matrix = np.eye(4, k=1)
print(matrix)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [9]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, np.arange(1, 5))
print(matrix)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [10]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [11]:
random_matrix = np.random.rand(10, 10)
mean_rows = np.mean(random_matrix, axis=1, keepdims=True)
result_matrix = random_matrix - mean_rows
print(result_matrix)

[[ 0.00587368  0.06431478 -0.05555117 -0.45118466 -0.12017139  0.33891826
   0.33236593  0.35131885 -0.5323982   0.06651393]
 [ 0.47208795 -0.02559992 -0.02198139  0.11012434 -0.29406496 -0.07720613
   0.12543378  0.09334268 -0.12371841 -0.25841795]
 [-0.32792071 -0.29545664  0.39944753 -0.38629231 -0.07840914  0.47953674
  -0.0092272   0.44455416 -0.29690287  0.07067043]
 [-0.34165733  0.25586752  0.10485684  0.29220708  0.0574477  -0.46232751
   0.12714188  0.15962589  0.10704895 -0.30021102]
 [-0.37206909  0.0662816   0.10951329  0.07053458 -0.31347536  0.42054277
   0.28334088  0.08553066 -0.03521484 -0.31498448]
 [ 0.35196748 -0.26022491 -0.20794525  0.32119452 -0.13713646 -0.5127159
   0.4601021   0.04324706 -0.12026976  0.06178112]
 [ 0.07858305  0.31751267  0.23168071 -0.31105509  0.16210889 -0.2399837
  -0.410899   -0.382575    0.29410747  0.26052001]
 [-0.25826325  0.24939317 -0.31453219  0.3979026  -0.31240463 -0.17460753
   0.0971885   0.52201052 -0.28276638  0.0760792 ]
 [

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [12]:
random_matrix = np.random.rand(10, 10)
median_cols = np.median(random_matrix, axis=0, keepdims=True)
result_matrix = random_matrix - median_cols
print(result_matrix)

[[-0.30999765 -0.54533769  0.39917482  0.42575761 -0.02448512  0.52574582
   0.0268417   0.12079198 -0.34701355 -0.05385663]
 [-0.13753771 -0.30092165  0.0634119   0.09149759  0.27806437 -0.08649667
  -0.20706712 -0.38345976  0.14796462  0.14947577]
 [-0.0802532   0.40374901 -0.04052857 -0.00429538  0.45238171 -0.04944577
   0.24079543  0.10360292 -0.17177806 -0.42211075]
 [ 0.37307517  0.39794513  0.03500539  0.00331284 -0.11223513 -0.19092262
   0.02378641 -0.10360292 -0.26869909 -0.25952851]
 [ 0.3559263   0.24079968 -0.23760874 -0.31045202  0.28030764  0.37829714
  -0.55924793 -0.50317042  0.12682052 -0.44253976]
 [-0.26530606  0.35970216  0.54348985  0.29883693 -0.2300334   0.23606712
  -0.59541883  0.16755987 -0.44635935 -0.42422801]
 [-0.11447788 -0.36931249 -0.03500539 -0.24011316  0.02448512  0.01122725
  -0.42270504 -0.50506397  0.1527921   0.05385663]
 [ 0.0802532   0.32838011 -0.06383168 -0.04090771  0.034668    0.59250575
   0.22021381  0.31525983 -0.03827254  0.16603961]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [26]:
import numpy as np

matrix = np.random.rand(5, 5)

row_max = np.max(matrix, axis=1)
row_min = np.min(matrix, axis=1)

result = np.concatenate((matrix, np.column_stack((row_max, row_min))), axis=1)

print(result)

[[0.51843373 0.37347512 0.42684038 0.51621152 0.20760917 0.51843373
  0.20760917]
 [0.27974003 0.73974344 0.09377582 0.96621994 0.11499162 0.96621994
  0.09377582]
 [0.37173354 0.84949692 0.25895023 0.58230501 0.9435173  0.9435173
  0.25895023]
 [0.88859921 0.11865744 0.74674478 0.40667026 0.23180493 0.88859921
  0.11865744]
 [0.64219496 0.88290178 0.29495826 0.59494078 0.06572702 0.88290178
  0.06572702]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [ ]:
import numpy as np

vector = np.arange(1, 52)


odd_numbers = vector[vector % 2 != 0]
even_numbers = vector[vector % 2 == 0]

print("\nНечетные числа:\n", odd_numbers)
print("\nЧетные числа:\n", even_numbers)


odd_numbers_matrix = odd_numbers[:25].reshape(5, 5)
even_numbers_matrix = even_numbers.reshape(5, 5)


product_matrix = np.dot(odd_numbers_matrix, even_numbers_matrix.T)

try:
    inverse_matrix = np.linalg.inv(product_matrix)
    print("\nПроизведение матриц:\n", product_matrix)
    print("\nОбратная матрица:\n", inverse_matrix)
except np.linalg.LinAlgError:
    print("Обратная матрица не существует.")




Нечетные числа:
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51]

Четные числа:
 [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]

Произведение матриц:
 [[  190   440   690   940  1190]
 [  490  1240  1990  2740  3490]
 [  790  2040  3290  4540  5790]
 [ 1090  2840  4590  6340  8090]
 [ 1390  3640  5890  8140 10390]]

Обратная матрица:
 [[ 2.47390116e+12 -2.19902326e+12 -2.19902326e+12  1.09951163e+12
   8.24633721e+11]
 [-1.92414535e+12 -0.00000000e+00  4.39804651e+12 -1.09951163e+12
  -1.37438953e+12]
 [-2.19902326e+12  4.39804651e+12 -2.19902326e+12 -0.00000000e+00
   4.88281250e-04]
 [ 2.74877907e+11 -0.00000000e+00 -0.00000000e+00 -1.09951163e+12
   8.24633721e+11]
 [ 1.37438953e+12 -2.19902326e+12 -0.00000000e+00  1.09951163e+12
  -2.74877907e+11]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [33]:
import numpy as np


matrix = np.zeros((8, 8), dtype=int)


matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
